name: FAntiXRay
main: me.FurH.FAntiXRay.FAntiXRay
version: 2.7.1
author: FurmigaHumana
description: Modify chunk sending to prevent xray mod.
softdepend: ['ProtocolLib', 'NoLagg', 'FCoreLib']
commands:
  fantixray:
    aliases: [antixray, ax, axr]
    description: FAntiXRay Commands
    usage: /FAntiXRay help
permissions:
  FAntiXRay.ClearCache:
    default: op
  FAntiXRay.SeeCache:
    default: op
  FAntiXRay.Reload:
    default: op
  FAntiXRay.Deobfuscate:
    default: op
  FAntiXRay.Quiet.Deobfuscate:
    default: op
  FAntiXRay.Updates:
    default: op