name: FAntiXRay
main: me.FurH.FAntiXRay.FAntiXRay
version: 2.3
author: FurmigaHumana
description: Modify chunk sending to prevent xray mod.
softdepend: ['ProtocolLib', 'NoLagg']
commands:
  fantixray:
    aliases: [antixray, ax, axr]
    description: FAntiXRay Commands
    usage: /FAntiXRay help