Options:
  ## Engine Mode, set to 0, 1, 2, 3 or 4. Check the plugin's description for more information.
  EngineMode: 0
  ## Update Radius, set it between 0 or 3. Higher this value is, higher will be the cpu usage.
  UpdateRadius: 1

Darkness:
  ## Enabled, if true, all blocks that is in the dark will be obfuscated
  Enabled: false
  ## BrightOnly, if true, the block will be update only if it have a light level higher then 0
  BrightOnly: false
  ## BrightRadius, the radius around the light to be updated, Higher this value is, higher will be the cpu usage.
  BrightRadius: 8
  ## UpdateOn, the block id that will cast the update when placed
  UpdateOn: 50, 51, 89
  ## ExtraBlocks, the extra blocks to be obfuscated if it is in the dark
  ExtraBlocks:
    - 5
    - 4
    - 30
    - 46
    - 47
    - 48
    - 49
    - 52
    - 54
    - 66
    - 85
    - 101

## Set which events will be used to update the blocks (Deobfuscate)
## OnBlockBreak is enabled by default and cannot be disabled, those are just extra!
## More events will use more resources, but will prevent blocks from not being deobfuscated.
UpdateEvents:
  ## Update blocks when player put a block
  onBlockPlace: false
  ## Update blocks on explosion
  onBlockExplosion: false
  ## Update blocks on damage
  onBlockDamage: false
  ## Update blocks when piston moves them
  onBlockPiston: false
  ## Update blocks on physics
  onBlockPhysics: false

Permissions:
  ## OpHasPerm, if true, op players will have all permissions
  OpHasPerm: false

Updater:
  ## Updater, if true, this plugin will check for updates automatically
  Enabled: true

Lists:
  ## Random Blocks, list here, all the blocks used on engine mode 2
  RandomBlocks:
    - 15
    - 56
  ## Hidden Blocks, list here, all the blocks that will be obfuscated by engine mode 0 and 1
  HiddenBlocks:
    - 14
    - 15
    - 16
    - 21
    - 56
    - 73
    - 74
    - 129
  ## Disabled Worlds, list here, all the worlds that will not be protected by this plugin.
  DisabledWorlds:
    - world_flat
    - world_nether
    - world_the_end