Options:
  ## Engine Mode, set to 0, 1, or 2.
  ## Engine Mode 0 > Hide all block in the HiddenBlocks list even if there is nothing blocking your view from it.
  ## Engine Mode 1 > Hide all blocks in the HiddenBlocks list that doesn't have air in one of its sides.
  ## Engine Mode 2 > Replace all stones that doesn't have air in one of its sides by a random block.
  ## Engine Mode 3 > Almost like 2 but with less random ores.
  ## Engine Mode 4 > Almost like 3 but it will also hide exposed ores transforming then into a stone, perfect to use with ChestHider > Obfuscated: true
  EngineMode: 0
  ## Update Radius, Higher this value is, higher will be the cpu usage.
  UpdateRadius: 1
  ## FakeCaves, set Enabled to true to generate fake caves in way to prevent xray texture pack and cavefinders.
  FakeCaves:
    ## It **might** cause fps drops on the client side and also a little bit more of cpu on the server si
    Enabled: false
    ## Intensity, the intensity of caves to generate, higher this value is, more fake caves you will have
    Intensity: 10
    
Cache:
  ## Enabled, if true, the cache system will be activated
  Enabled: false
  ## FileCallGC, the amount of files to process before suggesting a gc [prevent too many open files]
  FileCallGC: 100
  ## SizeLimit, set the size limit of the cache folder in MB, 0 Will disable it.
  SizeLimit: 5120
  ## The level of compression used on the cache, higher this value is, slower the cache will be and more resources will be required to read/write.
  Compress:
    ## 0 = No Compression (Ultra fast, higher sizes), 9 = Maximum compression (Slower, more resources needed, smaller sizes)
    Level: 1

Darkness:
  ## Enabled, if true, all blocks that is in the dark will be obfuscated (By default, the plugin will check for transparent blocks (air), if this is true, it will check the light level)
  ## This mode will replace all blocks from the HiddenBlocks and ExtraBlocks lists by a stone if the light level is 0.
  Enabled: false
  ## LightUpdate, if true, if you place a light souce (listed on UpdateOn) an update will be cast
  LightUpdate: false
  ## BrightRadius, the radius around the light to be updated, Higher this value is, higher will be the cpu usage.
  BrightRadius: 8
  ## UpdateOn, the block id that will cast the update when placed
  UpdateOn: 50, 51, 89
  ## ExtraBlocks, the extra blocks to be obfuscated if it is in the dark
  ExtraBlocks:
    - 4
    - 47
    - 48
    - 49
    - 52
    - 54
    - 98

ChestHider:
  ## Enabled, if true, all chest will turn into a stone, when the player get close it will turn back into a chest
  ## This function will create an extra thread for each player, and might use a bit of CPU.
  Enabled: false
  ## Interval, the interval in ticks per second to update the chests around the player
  Interval: 10
  ## Radius, the radius around the player to search for chests
  Radius: 10
  ## WalkMinimum, the minimum distance the player has to walk to fire the update
  WalkMinimum: 1
  ## Obfuscated, if true, visible obfuscated blocks around the player will be revealed.
  Obfuscated: false

## Set which events will be used to update the blocks (Deobfuscate)
## OnBlockBreak is enabled by default and cannot be disabled, those are just extra!
## More events will use more resources, but will prevent blocks from not being deobfuscated.
UpdateEvents:
  ## Update blocks when player put a block
  onBlockPlace: false
  ## Update blocks on explosion
  onBlockExplosion: false
  ## Update blocks on damage
  onBlockDamage: false
  ## Update blocks when piston moves them
  onBlockPiston: false
  ## Update blocks on physics
  onBlockPhysics: false
  ## ThreadedUpdate, if true, the block update will be threaded.
  ThreadedUpdate: true

Permissions:
  ## OpHasPerm, if true, op players will have all permissions
  OpHasPerm: false

Updater:
  ## Updater, if true, this plugin will check for updates automatically
  Enabled: true

Lists:
  ## Random Blocks, list here, all the blocks used on engine mode 2
  RandomBlocks:
    - 5
    - 14
    - 15
    - 16
    - 21
    - 22
    - 41
    - 42
    - 47
    - 48
    - 49
    - 56
    - 57
    - 98
    - 129
    - 133
  ## Hidden Blocks, list here, all the blocks that will be obfuscated by engine mode 0 and 1
  HiddenBlocks:
    - 14
    - 15
    - 16
    - 21
    - 56
    - 73
    - 74
    - 129
  ## Disabled Worlds, list here, all the worlds that will not be protected by this plugin.
  DisabledWorlds:
    - world_flat
    - world_nether
    - world_the_end