Options:
  ## Engine Mode, set to 0, 1 or 2. Check the plugin's description for more information.
  EngineMode: 1
  ## Update Radius, set it between 0 or 3. Higher this value is, higher will be the cpu usage.
  UpdateRadius: 1

## Set which events will be used to update the blocks (Deobfuscate)
## OnBlockBreak is enabled by default and cannot be disabled, those are just extra!
## More events will use more resources, but will prevent blocks from not being deobfuscated.
UpdateEvents:
  ## Update blocks when player put a block
  onBlockPlace: false
  ## Update blocks on explosion
  onBlockExplosion: false
  ## Update blocks on damage
  onBlockDamage: false
  ## Update blocks when piston moves them
  onBlockPiston: false
  ## Update blocks on physics
  onBlockPhysics: false

Cache:
  ## Enabled, if true, the cache system will be activated
  Enabled: true
  ## SizeLimit, set the size limit of the cache folder in MB, 0 Will disable it.
  SizeLimit: 5120
  ## WritesPerSec, set the number of files to be written per second
  WritesPerSec: 10
  ## The level of compression used on the cache, higher this value is, slower the cache will be and more resources will be required to read/write.
  Compress:
    ## 0 = No Compression (Ultra fast, higher sizes), 9 = Maximum compression (Slower, more resources needed, smaller sizes)
    Level: 1
  
Permissions:
  ## OpHasPerm, if true, op players will have all permissions
  OpHasPerm: true

Updater:
  ## Updater, if true, this plugin will check for updates automatically
  Enabled: true

Lists:
  ## Random Blocks, list here, all the blocks used on engine mode 2
  RandomBlocks:
    - 15
    - 56
  ## Hidden Blocks, list here, all the blocks that will be obfuscated by engine mode 0 and 1
  HiddenBlocks:
    - 14
    - 15
    - 16
    - 21
    - 56
    - 73
    - 74
    - 129
  ## Disabled Worlds, list here, all the worlds that will not be protected by this plugin.
  DisabledWorlds:
    - world_nether
    - world_the_end